runtime: nodejs18
env: standard

instance_class: F1

env_variables:
  DB_HOST: "YOUR_CLOUD_SQL_IP"
  DB_USER: "root"
  DB_PASSWORD: "YOUR_DB_PASSWORD"
  DB_NAME: "flashcard_db"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_idle_instances: 1

handlers:
- url: /.*
  script: auto
  secure: always 